### ISSUE TITLE
amqp_ascoltatore ERROR ECONNREFUSED 127.0.0.1:5672

### ISSUE THREAD

**Issue by abdoutech93** [saikath/Mqtt-Example-using-javascript-nodejs#1]
I tried to launch the MQTT Server over amqp instead of MangoDB but I got this error :

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)
Emitted 'error' event at:
    at Connection.<anonymous> (C:\Users\Soal Abdeldjallil\Desktop\Mqtt-Server\node_modules\mosca\node_modules\ascoltatori\lib\amqp_ascoltatore.js:69:12)
    at Connection.emit (events.js:185:15)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)

**Comment by saikath** [comment]
please share the code base where you have configured it.

**Comment by abdoutech93** [comment]
I solved the problem by using only websockets and i disabled the persistance and the backend module. 
thank you so much

**Comment by saikath** [comment]
okay good luck :)
